import React, { useMemo, useState } from "react";

const categories = ["Top stories", "Markets", "Trade", "Energy", "Agriculture", "Technology", "Infrastructure", "Policy"];
const stories = [
  {id:"evt-001",category:"Trade",location:"East Africa",title:"Regional trade corridor changes could cut landed costs for selected import categories",summary:"Policy, port and logistics reporting is grouped into one event cluster with the sectors most exposed to the change.",sources:["Reuters","Business Daily","Port Authority","+5"],freshness:"18 min ago",confidence:94,opportunity:"Import substitution / distribution",why:"Lower landed costs can alter distributor margins before retail pricing adjusts.",action:"Map HS codes → active importers → local price spread",tone:"blue"},
  {id:"evt-002",category:"Energy",location:"Kenya",title:"Grid and storage investment accelerates as industrial power demand rises",summary:"Multiple reports point to a near-term procurement cycle across storage, controls and industrial power equipment.",sources:["Energy Ministry","The EastAfrican","Company filings","+4"],freshness:"42 min ago",confidence:90,opportunity:"Supplier / contractor intelligence",why:"Projects create purchase orders before they show up in broad economic statistics.",action:"Extract projects → contractors → equipment categories",tone:"amber"},
  {id:"evt-003",category:"Agriculture",location:"Kenya",title:"Produce price dispersion widens between major growing regions and Nairobi",summary:"Wholesale price signals show a widening regional spread that may support short-haul trading after route costs are verified.",sources:["Market bulletins","County feeds","Trader reports","+6"],freshness:"1 hr ago",confidence:86,opportunity:"Trade route probe",why:"Price spread is meaningful only after route economics and buyer depth are verified.",action:"Run CI-001 local market adapter",tone:"green"},
  {id:"evt-004",category:"Technology",location:"Africa",title:"AI infrastructure spending shifts from pilots toward operating workloads",summary:"Cloud, data-center and enterprise announcements suggest a change in buying behavior toward recurring deployment.",sources:["Company releases","TechCabal","Bloomberg","+8"],freshness:"2 hrs ago",confidence:91,opportunity:"B2B services / infrastructure",why:"Recurring workloads create demand for integration, monitoring and vertical applications.",action:"Send to opportunity review",tone:"violet"},
  {id:"evt-005",category:"Infrastructure",location:"East Africa",title:"New transport projects reshape commercial catchment areas around secondary cities",summary:"Road and logistics projects are being connected to land, warehousing, retail and agricultural-flow implications.",sources:["Government notices","Local press","Tender data","+7"],freshness:"3 hrs ago",confidence:88,opportunity:"Land / logistics / services",why:"Accessibility changes can move economic activity before formal investment reports catch up.",action:"Generate corridor opportunity map",tone:"slate"}
];
const briefs=[{label:"FX",value:"KES volatility",note:"Watch importer margins"},{label:"PORTS",value:"Mombasa flow",note:"3 sectors accelerating"},{label:"FOOD",value:"Regional spread",note:"2 trade probes active"},{label:"TECH",value:"AI spend",note:"Enterprise demand rising"}];

export default function IntelligenceNewsroom(){
  const [activeCategory,setActiveCategory]=useState("Top stories");
  const [selected,setSelected]=useState(stories[0]);
  const [mode,setMode]=useState("Newsroom");
  const visible=useMemo(()=>activeCategory==="Top stories"?stories:stories.filter(s=>s.category===activeCategory),[activeCategory]);
  return <div className="ain-page">
    <header className="ain-header"><div className="ain-header-inner">
      <a className="ain-brand" href="/"><span className="ain-brand-mark">A</span><span><strong>Atlas Intelligence</strong><small>Autonomous Newsroom Prototype</small></span></a>
      <div className="ain-search"><span>⌕</span><input placeholder="Search events, companies, sectors, countries..."/><kbd>⌘ K</kbd></div>
      <div className="ain-header-actions"><span className="ain-live"><i/> LIVE</span><button className="ain-icon-button">◔</button><div className="ain-avatar">000</div></div>
    </div></header>
    <nav className="ain-tabs"><div className="ain-tabs-inner">{categories.map(c=><button key={c} className={activeCategory===c?"active":""} onClick={()=>setActiveCategory(c)}>{c}</button>)}</div></nav>
    <main className="ain-main">
      <section className="ain-intro"><div><div className="ain-kicker">AFRICA BUSINESS & ECONOMIC INTELLIGENCE</div><h1>What happened. Why it matters. What to do next.</h1><p>Stories are clustered into events, corroborated across sources, ranked by economic significance, and converted into actionable intelligence.</p></div><div className="ain-mode-toggle">{["Newsroom","Intelligence","Opportunities"].map(x=><button key={x} className={mode===x?"active":""} onClick={()=>setMode(x)}>{x}</button>)}</div></section>
      <section className="ain-ticker-grid">{briefs.map(b=><article key={b.label} className="ain-ticker-card"><span>{b.label}</span><strong>{b.value}</strong><small>{b.note}</small></article>)}</section>
      <section className="ain-layout"><div className="ain-feed"><div className="ain-section-heading"><div><span className="ain-pulse-dot"/><h2>{activeCategory}</h2></div><span>Ranked by significance × freshness × corroboration</span></div>
        {visible.length===0&&<div className="ain-empty">No prototype events in this category yet.</div>}
        {visible.map((s,i)=><article key={s.id} className={`ain-story ${selected.id===s.id?"selected":""}`} onClick={()=>setSelected(s)}><div className={`ain-story-visual tone-${s.tone}`}><span>{s.category}</span><strong>{String(i+1).padStart(2,"0")}</strong><small>{s.location}</small></div><div className="ain-story-body"><div className="ain-story-meta"><span>{s.category}</span><span>•</span><span>{s.location}</span><span>•</span><span>{s.freshness}</span></div><h3>{s.title}</h3><p>{s.summary}</p><div className="ain-story-footer"><div className="ain-source-stack">{s.sources.map((x,j)=><span key={x} className={j===s.sources.length-1?"more":""}>{x}</span>)}</div><div className="ain-confidence"><span>{s.confidence}% corroborated</span><div><i style={{width:`${s.confidence}%`}}/></div></div></div></div></article>)}
      </div><aside className="ain-rail"><div className="ain-panel"><div className="ain-panel-label">SELECTED EVENT</div><h3>{selected.title}</h3><div className="ain-event-id">{selected.id.toUpperCase()} · {selected.sources.length+4} linked reports</div><div className="ain-detail-block"><span>WHY IT MATTERS</span><p>{selected.why}</p></div><div className="ain-detail-block opportunity"><span>OPPORTUNITY SIGNAL</span><strong>{selected.opportunity}</strong><p>{selected.action}</p></div><button className="ain-primary-button">Open intelligence brief →</button></div>
      <div className="ain-panel"><div className="ain-panel-heading-row"><div><div className="ain-panel-label">FACTORY AUTONOMY</div><h3>Newsroom operator</h3></div><span className="ain-status">L2 DEMO</span></div><div className="ain-pipeline">{["Collect","Cluster","Verify","Rank","Explain","Opportunity"].map((x,i)=><div key={x} className={i<5?"active":"queued"}><i/><span>{x}</span></div>)}</div><div className="ain-run-stats"><div><strong>128</strong><span>sources watched</span></div><div><strong>43</strong><span>events clustered</span></div><div><strong>7</strong><span>signals escalated</span></div></div><small className="ain-demo-note">Prototype metrics shown for UI evaluation; live ingestion is the next implementation layer.</small></div></aside></section>
      <section className="ain-opportunity-strip"><div><span className="ain-panel-label">THE DIFFERENTIATOR</span><h2>News → Event → Economic significance → Opportunity → Factory action</h2></div><div className="ain-flow">{["NEWS","EVENT","IMPACT","OPPORTUNITY","ACTION"].map((x,i)=><React.Fragment key={x}><span>{x}</span>{i<4&&<b>→</b>}</React.Fragment>)}</div></section>
    </main>
  </div>;
}
